<?php

function cncdkoalect_menu() {
  $items = [];

  $items['cncdkoalect'] = [
    'title'            => 'CNCD Koalect',
    'page callback'    => 'cncdkoalect_process',
    'access arguments' => ['access content'],
    'description' => t('CNCD KOALECT'),
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

function cncdkoalect_process() {
  header('Content-Type: application/json');

  $data = cncdkoalect_getBlankReturnObject();

  try {
    $data->status_message = "test message";
  }
  catch (Exception $e) {
    $data->status = $e->getCode();
    $data->status_message = $e->getMessage();
  }

  return json_encode($data);
}

function cncdkoalect_getBlankReturnObject() {
  $o = new stdClass();

  $o->status = 200;
  $o->status_message = '';
  $o->orders = [];

  return $o;
}
